---
- name: Check JBoss/WildFly installation and version
  hosts: all
  vars: 
        excel_loc : "YOUR LOCATION"
        fuse_running: "false"
  tasks:
# JBoss/Wildfly
      - name: Check for running JBoss/Wildfly
        shell: "ps aux | grep -o -m1 'jboss\\.home\\.dir=[^[:space:]]*' | cut -d= -f2"
        register: jboss_home_dir
        failed_when:
            - jboss_home_dir.stdout_lines|length == 0

      - name: Read file contents
        slurp:
          src: "{{jboss_home_dir.stdout}}/version.txt"
        register: file_contents


# Fuse/Apache Camel
      #- name: Check for running Fuse/Apache Camel as an pid
      #  shell: "ps aux | grep -q fuse"
      #  register: fuse_running

      #- debug: var=fuse_running

      #- name: Fuse state
      #  set_fact: 
      #   fuse_running: false
      #  when: 
      #   - fuse_running.stdout_lines|length > 0

# Generate report, collects data for reporting
      - name: Creating excel spreadsheet
        file:
         path: "{{ excel_loc }}"
         state: touch
        delegate_to: localhost
        run_once: true 

      - name: Adding initial line to spreadsheet
        lineinfile:
         insertafter: EOF
         dest: "{{ excel_loc }}"
         line: "Hostname,OS,Version,Fuse-Installed,Jboss-Installed,vcpu"
        delegate_to: localhost
        run_once: true           

      - name: Adding test values to spreadsheet
        lineinfile:
         insertafter: EOF
         dest: "{{ excel_loc }}"
         line: "{{ ansible_hostname }},{{ ansible_distribution}},{{ansible_distribution_version }},{{ ansible_hostname }},{{file_contents.content | b64decode}},{{ansible_processor_vcpus}}"
        delegate_to: localhost